In [1]:
li=[]
for i in range(1,100,5):
    li.append(int(input()))
print(li)
print(li[-3:])

1
2
3
4
5
6
7
8
9
13
42
5
4
56
75
77
57
68
68
68
[1, 2, 3, 4, 5, 6, 7, 8, 9, 13, 42, 5, 4, 56, 75, 77, 57, 68, 68, 68]
[68, 68, 68]


In [6]:
li=[]
n=int(input("Enter the no of elements needed: "))
k=int(input("Enter the Start: "))
for i in range(0,n):
      li.append(k)
      k=k+5
print(li)
print(li[-3:])
print(li[17:21:1])

Enter the no of elements needed: 20
Enter the Start: 5
[5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]
[90, 95, 100]
[90, 95, 100]


In [2]:
import numpy as np
arr=np.arange(100)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
print(arr.shape)

(100,)


In [10]:
print(arr.ndim)

1


In [11]:
print(arr.size)

100


In [23]:
b=np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [24]:
c=np.ones((3,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
b=np.array([[1,2,6],[3,4,7],[9,]])
print(b)

In [26]:
n=np.zeros((3,3))
print(n)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
m=np.eye((3))
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
s=np.ones((4,3,2))
print(s)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [31]:
v=np.diag([1,2,3])
print(v)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [32]:
e=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(e)
z=np.diag(e)
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [33]:
y=np.linspace(5,10,5)
print(y)

[ 5.    6.25  7.5   8.75 10.  ]


In [34]:
o=np.linspace(5,12,5)
print(o)

[ 5.    6.75  8.5  10.25 12.  ]


In [37]:
u=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(u)
print(u[1,1])
print(u[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
9


In [47]:
w=np.arange(1,11)
w[4:10]=10
print(w)

[ 1  2  3  4 10 10 10 10 10 10]


In [51]:
li=[1,2,3,4,5,6,7,8,9,10]
for i in range(4,10,1):
    li[i]=10
print(li)

[1, 2, 3, 4, 10, 10, 10, 10, 10, 10]


In [52]:
li=[1,2,3,4,5,6,7,8,9,10]
a=np.array(li)
a[5:]=10
print(a)

[ 1  2  3  4  5 10 10 10 10 10]
